### ISSUE TITLE
🐛 Bug: Recommended config needs an extra '.default' access in CJS

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/eslint-plugin-expect-type#490]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/issues?q=is%3Aissue) and found none that matched my issue.

### Expected

In a CommonJS config (e.g. `eslint.config.cjs`), you should be able to:

```js
const expectType = require("eslint-plugin-expect-type/configs/recommended");
```

### Actual

...but the source file only has a `default` export, which isn't transpiled with a compatibility layer:

https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/blob/039e3d83bf2d1b3aeb36fc5af603d0694e0ff335/src/configs/recommended.ts#L10

### Additional Info

Noted by @fasttime in https://github.com/JoshuaKGoldberg/eslint-plugin-expect-type/issues/486#issuecomment-2346362370. Therefore:

Co-authored-by: @fasttime

**Comment by JoshuaKGoldberg** [comment]
Note that this isn't as simple as adding `export { rules, recommended }` to the file. Trying that yields:

```plaintext
Oops! Something went wrong! :(

ESLint: 9.10.0

ConfigError: Config (unnamed): Unexpected key "default" found.
    at rethrowConfigError (/Users/josh/repos/repros/node_modules/@eslint/config-array/dist/cjs/index.cjs:303:8)
    at /Users/josh/repos/repros/node_modules/@eslint/config-array/dist/cjs/index.cjs:1098:5
    ...
```

For now, I'm going to just treat this as a docs issue. I'm not motivated to make changes or add in anything fancy for CommonJS support. Especially since ESLint supports `eslint.config.mjs` files to use ESM in non-ESM repos.
