### ISSUE TITLE
"host.fileExists is not a function" with TypeScript 4.8.4

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/eslint-plugin-expect-type#62]
### 🐛 Bug Report

- `eslint-plugin-expect-type` version: 0.2.0
- ESLint version: 8.24.0
- Node version: 18.7.0
- TypeScript version: 4.8.4

#### Actual Behavior

```shell
yarn lint
```

```
Oops! Something went wrong! :(

ESLint: 8.24.0

TypeError: Error while loading rule 'expect-type/expect': host.fileExists is not a function
Occurred while linting /Users/josh/repos/typescript-static-analysis-hidden-gems/src/linting/types.test.ts
    at Object.fileExists (/Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:167620:63)
    at host.fileExists (/Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:117500:47)
    at getPackageJsonInfo (/Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:44461:37)
    at loadModuleFromSpecificNodeModulesDirectory (/Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:45001:27)
    at loadModuleFromImmediateNodeModulesDirectory (/Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:44982:58)
    at /Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:44972:39
    at Object.forEachAncestorDirectory (/Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:8370:26)
    at loadModuleFromNearestNodeModulesDirectoryWorker (/Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:44966:19)
    at loadModuleFromNearestNodeModulesDirectory (/Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:44958:16)
    at tryResolve (/Users/josh/repos/typescript-static-analysis-hidden-gems/node_modules/typescript/lib/typescript.js:44053:34)
```

#### Expected Behavior

This should still work in newer versions of TypeScript.

Downgrading to `typescript@4.7.4` fixes the issue.

#### Reproduction

https://github.com/JoshuaKGoldberg/typescript-static-analysis-hidden-gems/pull/2/commits/bc57f20cc53d8ee0f2388e3b59709be8d859c104

**Comment by JoshuaKGoldberg** [comment]
Oh, dup of #60. I just never published a new version.
